// The command table: the one map from every command of the manifest to its handler, or to NOT_AVAILABLE_YET while
// its feature is not built (its doors are drawn disabled with "not available yet"). CommandTable has a key for every
// CommandId (src/generated/ids.ts), so a missing or an extra entry, or a handler under another command's key, is a
// type error (src/app/commands.typecheck.ts proves it). The order is the manifest's.
import { NOT_AVAILABLE_YET, always, type CommandTable, type PredicateTable } from '../core/commands/registry.ts';
import { canRedo, canUndo, redoCommand, undoCommand } from '../core/history/history.ts';
import { toggleHiddenCommand } from '../core/nodes/flags.ts';
import { openProject, saveProject } from '../core/project/archive.ts';
import {
  addCommand,
  clearSelectionCommand,
  hasSelection,
  singleSelection,
  marqueeCommand,
  selectCommand,
  toggleCommand,
  walkFirstChildCommand,
  walkNextSiblingCommand,
  walkParentCommand,
  walkPreviousSiblingCommand,
} from '../core/selection/selection.ts';
import { duplicateCommand } from '../core/structure/duplicate.ts';
import { insertCommand } from '../core/structure/insert.ts';
import { canNestIntoPrevious, moveDownCommand, moveToCommand, moveUpCommand, nestIntoPreviousCommand, promoteCommand } from '../core/structure/move.ts';
import { deleteCommand } from '../core/structure/remove.ts';
import { canUnwrap, unwrapCommand, wrapColumnCommand, wrapRowCommand } from '../core/structure/wrap.ts';
import { setTextCommand } from '../core/text/text.ts';
import { cancelEdit, insertLineBreak, singleTextSelection, startEdit } from '../editor/canvas/text-edit.ts';
import { cancelDrag } from '../editor/drag/drag-session.ts';
import { focusActivate, focusFirst, focusLast, focusNext, focusPrevious } from '../editor/focus/focus.ts';
import { setExpanded } from '../editor/layers/tree.ts';
import { contextMenuOpen } from '../editor/menus/context-menu.ts';
import { dismiss } from '../editor/menus/overlays.ts';
import { setLanguage, setTheme } from '../editor/preferences/preferences.ts';
import type { EditorUi } from '../editor/state.ts';
import { setWorkbenchState } from '../editor/workspace/layout.ts';
import { collapseDocks, setPanelOpen, toggleInspector, toggleLeftDock } from '../editor/workspace/panels.ts';

export const COMMANDS = {
  'animation.create': NOT_AVAILABLE_YET,
  'animation.rename': NOT_AVAILABLE_YET,
  'animation.delete': NOT_AVAILABLE_YET,
  'animation.addKeyframe': NOT_AVAILABLE_YET,
  'animation.moveKeyframe': NOT_AVAILABLE_YET,
  'animation.setKeyframeEasing': NOT_AVAILABLE_YET,
  'animation.deleteKeyframe': NOT_AVAILABLE_YET,
  'animation.setSettings': NOT_AVAILABLE_YET,
  'timeline.setPlayhead': NOT_AVAILABLE_YET,
  'timeline.play': NOT_AVAILABLE_YET,
  'timeline.pause': NOT_AVAILABLE_YET,
  'timeline.stop': NOT_AVAILABLE_YET,
  'timeline.toggleLoop': NOT_AVAILABLE_YET,
  'clipboard.copy': NOT_AVAILABLE_YET,
  'clipboard.paste': NOT_AVAILABLE_YET,
  'clipboard.cut': NOT_AVAILABLE_YET,
  'clipboard.copyStyle': NOT_AVAILABLE_YET,
  'clipboard.pasteStyle': NOT_AVAILABLE_YET,
  'colors.saveSwatch': NOT_AVAILABLE_YET,
  'colors.removeSwatch': NOT_AVAILABLE_YET,
  'tokens.create': NOT_AVAILABLE_YET,
  'tokens.update': NOT_AVAILABLE_YET,
  'tokens.rename': NOT_AVAILABLE_YET,
  'tokens.delete': NOT_AVAILABLE_YET,
  'classes.create': NOT_AVAILABLE_YET,
  'classes.apply': NOT_AVAILABLE_YET,
  'classes.detach': NOT_AVAILABLE_YET,
  'inspector.setStyleTarget': NOT_AVAILABLE_YET,
  'components.create': NOT_AVAILABLE_YET,
  'components.insertInstance': NOT_AVAILABLE_YET,
  'components.detach': NOT_AVAILABLE_YET,
  'element.setTag': NOT_AVAILABLE_YET,
  'element.setAttribute': NOT_AVAILABLE_YET,
  'element.setId': NOT_AVAILABLE_YET,
  'element.setClasses': NOT_AVAILABLE_YET,
  'element.setLink': NOT_AVAILABLE_YET,
  'element.setInputType': NOT_AVAILABLE_YET,
  'element.setLabelTarget': NOT_AVAILABLE_YET,
  'element.setCustomAttribute': NOT_AVAILABLE_YET,
  'element.removeCustomAttribute': NOT_AVAILABLE_YET,
  'element.setSvgMarkup': NOT_AVAILABLE_YET,
  'element.setEmbedMarkup': NOT_AVAILABLE_YET,
  'element.applyHtml': NOT_AVAILABLE_YET,
  'parts.toggle': NOT_AVAILABLE_YET,
  'parts.add': NOT_AVAILABLE_YET,
  'parts.move': NOT_AVAILABLE_YET,
  'parts.remove': NOT_AVAILABLE_YET,
  'table.addColumnAfter': NOT_AVAILABLE_YET,
  'table.addColumnEnd': NOT_AVAILABLE_YET,
  'table.removeColumn': NOT_AVAILABLE_YET,
  'table.addRowAfter': NOT_AVAILABLE_YET,
  'table.removeRow': NOT_AVAILABLE_YET,
  'interactions.add': NOT_AVAILABLE_YET,
  'interactions.update': NOT_AVAILABLE_YET,
  'interactions.remove': NOT_AVAILABLE_YET,
  'pages.add': NOT_AVAILABLE_YET,
  'pages.rename': NOT_AVAILABLE_YET,
  'pages.duplicate': NOT_AVAILABLE_YET,
  'pages.delete': NOT_AVAILABLE_YET,
  'pages.switch': NOT_AVAILABLE_YET,
  'files.createFolder': NOT_AVAILABLE_YET,
  'files.createFile': NOT_AVAILABLE_YET,
  'files.rename': NOT_AVAILABLE_YET,
  'files.move': NOT_AVAILABLE_YET,
  'files.delete': NOT_AVAILABLE_YET,
  'files.open': NOT_AVAILABLE_YET,
  'files.closeTab': NOT_AVAILABLE_YET,
  'files.upload': NOT_AVAILABLE_YET,
  'files.saveContent': NOT_AVAILABLE_YET,
  'assets.insertImageFile': NOT_AVAILABLE_YET,
  'focus.next': focusNext,
  'focus.previous': focusPrevious,
  'focus.first': focusFirst,
  'focus.last': focusLast,
  'focus.activate': focusActivate,
  'focus.nextRegion': NOT_AVAILABLE_YET,
  'focus.previousRegion': NOT_AVAILABLE_YET,
  'focus.canvas': NOT_AVAILABLE_YET,
  'ui.dismiss': dismiss,
  'position.setMode': NOT_AVAILABLE_YET,
  'geometry.resize': NOT_AVAILABLE_YET,
  'position.move': NOT_AVAILABLE_YET,
  'position.setAnchors': NOT_AVAILABLE_YET,
  'position.align': NOT_AVAILABLE_YET,
  'position.distribute': NOT_AVAILABLE_YET,
  'handle.step': NOT_AVAILABLE_YET,
  'canvas.setEditMode': NOT_AVAILABLE_YET,
  'history.undo': undoCommand,
  'history.redo': redoCommand,
  'layers.startRename': NOT_AVAILABLE_YET,
  'element.rename': NOT_AVAILABLE_YET,
  'element.toggleLock': NOT_AVAILABLE_YET,
  'element.toggleHidden': toggleHiddenCommand,
  'element.setLayerColor': NOT_AVAILABLE_YET,
  'page.openProperties': NOT_AVAILABLE_YET,
  'page.setSetting': NOT_AVAILABLE_YET,
  'project.newBlankPage': NOT_AVAILABLE_YET,
  'project.restoreVersion': NOT_AVAILABLE_YET,
  'project.takeOverEditing': NOT_AVAILABLE_YET,
  'project.save': saveProject,
  'project.open': openProject,
  'project.openFolder': NOT_AVAILABLE_YET,
  'project.importHtml': NOT_AVAILABLE_YET,
  'project.export': NOT_AVAILABLE_YET,
  'selection.select': selectCommand,
  'selection.clear': clearSelectionCommand,
  'selection.add': addCommand,
  'selection.toggle': toggleCommand,
  'selection.walkNextSibling': walkNextSiblingCommand,
  'selection.walkPreviousSibling': walkPreviousSiblingCommand,
  'selection.walkParent': walkParentCommand,
  'selection.walkFirstChild': walkFirstChildCommand,
  'selection.selectAllInContainer': NOT_AVAILABLE_YET,
  'selection.marquee': marqueeCommand,
  'contextMenu.open': contextMenuOpen,
  'element.insert': insertCommand,
  'element.moveTo': moveToCommand,
  'drag.levelUp': NOT_AVAILABLE_YET,
  'drag.levelDown': NOT_AVAILABLE_YET,
  'drag.cancel': cancelDrag,
  'element.moveUp': moveUpCommand,
  'element.moveDown': moveDownCommand,
  'element.wrapRow': wrapRowCommand,
  'element.wrapColumn': wrapColumnCommand,
  'element.nestIntoPrevious': nestIntoPreviousCommand,
  'element.promote': promoteCommand,
  'element.duplicate': duplicateCommand,
  'element.delete': deleteCommand,
  'element.unwrap': unwrapCommand,
  'element.createNaturalChild': NOT_AVAILABLE_YET,
  'hand.take': NOT_AVAILABLE_YET,
  'hand.aimNext': NOT_AVAILABLE_YET,
  'hand.aimPrevious': NOT_AVAILABLE_YET,
  'hand.climb': NOT_AVAILABLE_YET,
  'hand.descend': NOT_AVAILABLE_YET,
  'hand.drop': NOT_AVAILABLE_YET,
  'style.set': NOT_AVAILABLE_YET,
  'style.setSpacing': NOT_AVAILABLE_YET,
  'inspector.toggleSpacingLink': NOT_AVAILABLE_YET,
  'style.setBorder': NOT_AVAILABLE_YET,
  'style.setRadius': NOT_AVAILABLE_YET,
  'style.setBackgroundImage': NOT_AVAILABLE_YET,
  'style.setShadows': NOT_AVAILABLE_YET,
  'style.setFilter': NOT_AVAILABLE_YET,
  'style.setTransform': NOT_AVAILABLE_YET,
  'style.setAlignment': NOT_AVAILABLE_YET,
  'style.setCustomDeclarations': NOT_AVAILABLE_YET,
  'style.applyCssRule': NOT_AVAILABLE_YET,
  'style.reset': NOT_AVAILABLE_YET,
  'style.resetAll': NOT_AVAILABLE_YET,
  'field.step': NOT_AVAILABLE_YET,
  'field.scrub': NOT_AVAILABLE_YET,
  'field.setUnit': NOT_AVAILABLE_YET,
  'text.startEdit': startEdit,
  'text.set': setTextCommand,
  'text.cancelEdit': cancelEdit,
  'text.insertLineBreak': insertLineBreak,
  'text.toggleBold': NOT_AVAILABLE_YET,
  'text.toggleItalic': NOT_AVAILABLE_YET,
  'text.editLink': NOT_AVAILABLE_YET,
  'text.paste': NOT_AVAILABLE_YET,
  'text.selectAll': NOT_AVAILABLE_YET,
  'view.zoomIn': NOT_AVAILABLE_YET,
  'view.zoomOut': NOT_AVAILABLE_YET,
  'view.zoomReset': NOT_AVAILABLE_YET,
  'view.zoomTo': NOT_AVAILABLE_YET,
  'view.zoomFit': NOT_AVAILABLE_YET,
  'view.zoomAt': NOT_AVAILABLE_YET,
  'view.pan': NOT_AVAILABLE_YET,
  'view.setBreakpoint': NOT_AVAILABLE_YET,
  'view.setEditorView': NOT_AVAILABLE_YET,
  'view.setStyleState': NOT_AVAILABLE_YET,
  'view.enterPreview': NOT_AVAILABLE_YET,
  'view.exitPreview': NOT_AVAILABLE_YET,
  'view.toggleOutlines': NOT_AVAILABLE_YET,
  'view.toggleZones': NOT_AVAILABLE_YET,
  'view.toggleRulers': NOT_AVAILABLE_YET,
  'view.toggleSmartGuides': NOT_AVAILABLE_YET,
  'view.toggleEqualSpacing': NOT_AVAILABLE_YET,
  'grid.toggleColumns': NOT_AVAILABLE_YET,
  'grid.toggleRows': NOT_AVAILABLE_YET,
  'grid.toggleDots': NOT_AVAILABLE_YET,
  'grid.setSettings': NOT_AVAILABLE_YET,
  'guides.create': NOT_AVAILABLE_YET,
  'guides.move': NOT_AVAILABLE_YET,
  'guides.delete': NOT_AVAILABLE_YET,
  'guides.toggleLock': NOT_AVAILABLE_YET,
  'guides.toggleVisible': NOT_AVAILABLE_YET,
  'snap.setEnabled': NOT_AVAILABLE_YET,
  'snap.setSettings': NOT_AVAILABLE_YET,
  'workspace.openDialog': NOT_AVAILABLE_YET,
  'workspace.setPanelOpen': setPanelOpen,
  'workspace.toggleLeftDock': toggleLeftDock,
  'workspace.toggleInspector': toggleInspector,
  'workspace.collapseDocks': collapseDocks,
  'workspace.toggleDeveloperTools': NOT_AVAILABLE_YET,
  'workspace.reset': NOT_AVAILABLE_YET,
  'workspace.setWorkbenchState': setWorkbenchState,
  'workspace.setActiveTab': NOT_AVAILABLE_YET,
  'workspace.resizeSplitter': NOT_AVAILABLE_YET,
  'workspace.movePanel': NOT_AVAILABLE_YET,
  'quickPanel.setOffset': NOT_AVAILABLE_YET,
  'preferences.setLanguage': setLanguage,
  'preferences.setTheme': setTheme,
  'commandBar.open': NOT_AVAILABLE_YET,
  'palette.toggleGroup': NOT_AVAILABLE_YET,
  'palette.setDensity': NOT_AVAILABLE_YET,
  'layers.setExpanded': setExpanded,
  'layers.collapseAll': NOT_AVAILABLE_YET,
  'layers.expandAll': NOT_AVAILABLE_YET,
  'layers.expandOrFocusChild': NOT_AVAILABLE_YET,
  'layers.collapseOrFocusParent': NOT_AVAILABLE_YET,
  'layers.setRowDetails': NOT_AVAILABLE_YET,
  'inspector.toggleSection': NOT_AVAILABLE_YET,
  'inspector.setMode': NOT_AVAILABLE_YET,
  'inspector.reveal': NOT_AVAILABLE_YET,
  'codePanel.copyPane': NOT_AVAILABLE_YET,
  'codePanel.downloadPane': NOT_AVAILABLE_YET,
} as const satisfies CommandTable<EditorUi>;

// The availability predicates code has registered; a built command's predicate must be here (createStore checks it).
export const PREDICATES = { always, canUndo, canRedo, hasSelection, singleSelection, singleTextSelection, canUnwrap, canNestIntoPrevious } as const satisfies PredicateTable<EditorUi>;
