// The feature table (ARCHITECTURE.md): the one map from every feature of the manifest to its registration, in the
// order of manifest/features/. A feature is registered with registerFeature once it is built, and NOT_AVAILABLE_YET
// until then; a missing or an extra entry is a type error. Its doors, and the controls that stand for an item it
// brings (a palette entry), are usable only while it is registered (DESIGN.md "Build order"); the census fails a
// registered feature with no scenario, or one of whose scenarios cannot run or fails. Plain data: the runner and the
// census read it in Node.
import { NOT_AVAILABLE_YET, isRegistered, registerFeature, type FeatureTable } from '../core/commands/registry.ts';
import type { FeatureId } from '../generated/ids.ts';

export const FEATURES = {
  // 01 foundation
  'editor-shell': registerFeature('editor-shell'),
  'canvas-page-iframe': registerFeature('canvas-page-iframe'),
  // 02 structure editing
  'palette-click-insert': registerFeature('palette-click-insert'),
  'select-click': registerFeature('select-click'),
  'layers-tree': registerFeature('layers-tree'),
  'undo-redo': registerFeature('undo-redo'),
  'delete-element': registerFeature('delete-element'),
  'drag-reorder-canvas': registerFeature('drag-reorder-canvas'),
  'drag-drop-inside': registerFeature('drag-drop-inside'),
  'drag-level-keys-escape': registerFeature('drag-level-keys-escape'),
  'palette-drag-insert': registerFeature('palette-drag-insert'),
  'layers-drag': NOT_AVAILABLE_YET,
  'move-up-down': registerFeature('move-up-down'),
  'wrap-row-column': registerFeature('wrap-row-column'),
  'context-menu': registerFeature('context-menu'),
  'nest-into-previous': registerFeature('nest-into-previous'),
  'promote-out': registerFeature('promote-out'),
  duplicate: registerFeature('duplicate'),
  'clipboard-copy-paste': NOT_AVAILABLE_YET,
  'keyboard-tree-walk': registerFeature('keyboard-tree-walk'),
  'hand-keyboard-move': registerFeature('hand-keyboard-move'),
  'text-edit-inline': registerFeature('text-edit-inline'),
  'text-inline-formatting': registerFeature('text-inline-formatting'),
  'rename-element': registerFeature('rename-element'),
  'multi-select-click': registerFeature('multi-select-click'),
  unwrap: registerFeature('unwrap'),
  'marquee-select': registerFeature('marquee-select'),
  'multi-select-actions': NOT_AVAILABLE_YET,
  'select-container-children': registerFeature('select-container-children'),
  'lock-element': registerFeature('lock-element'),
  'hide-element': registerFeature('hide-element'),
  // 03 app and persistence
  'app-menu': NOT_AVAILABLE_YET,
  'ui-language': registerFeature('ui-language'),
  'autosave-restore': registerFeature('autosave-restore'),
  'unsaved-work-guard': NOT_AVAILABLE_YET,
  'autosave-crash-recovery': NOT_AVAILABLE_YET,
  'new-blank-page': NOT_AVAILABLE_YET,
  'autosave-corruption-recovery': NOT_AVAILABLE_YET,
  'multi-tab-guard': NOT_AVAILABLE_YET,
  'project-save-json': registerFeature('project-save-json'),
  'project-open-json': NOT_AVAILABLE_YET,
  // 04 inspector
  'inspector-panel': registerFeature('inspector-panel'),
  'inspector-number-fields': NOT_AVAILABLE_YET,
  'props-display': NOT_AVAILABLE_YET,
  'props-flex-container': NOT_AVAILABLE_YET,
  'props-grid-container': NOT_AVAILABLE_YET,
  'props-layout-item': NOT_AVAILABLE_YET,
  'props-spacing': NOT_AVAILABLE_YET,
  'props-size-overflow': NOT_AVAILABLE_YET,
  'props-position': NOT_AVAILABLE_YET,
  'color-picker': NOT_AVAILABLE_YET,
  'color-picker-oklch': NOT_AVAILABLE_YET,
  'color-swatches-eyedropper': NOT_AVAILABLE_YET,
  'props-typography': NOT_AVAILABLE_YET,
  'props-typography-advanced': NOT_AVAILABLE_YET,
  'props-background': NOT_AVAILABLE_YET,
  'gradient-editor': NOT_AVAILABLE_YET,
  'props-border-outline': NOT_AVAILABLE_YET,
  'props-effects-basic': NOT_AVAILABLE_YET,
  'shadow-editor': NOT_AVAILABLE_YET,
  'props-filters-clip': NOT_AVAILABLE_YET,
  'props-transforms': NOT_AVAILABLE_YET,
  'props-transition': NOT_AVAILABLE_YET,
  'props-more': NOT_AVAILABLE_YET,
  'props-attributes': NOT_AVAILABLE_YET,
  'inspector-provenance-reset': NOT_AVAILABLE_YET,
  'inspector-property-search': NOT_AVAILABLE_YET,
  'inspector-advanced-mode': NOT_AVAILABLE_YET,
  'inspector-add-property': NOT_AVAILABLE_YET,
  'semantic-tag-switch': NOT_AVAILABLE_YET,
  'quick-panel': NOT_AVAILABLE_YET,
  'multi-select-edit': NOT_AVAILABLE_YET,
  // 05 canvas handles
  'resize-handles': NOT_AVAILABLE_YET,
  'spacing-handles': NOT_AVAILABLE_YET,
  'radius-border-gap-handles': NOT_AVAILABLE_YET,
  'shadow-handles': NOT_AVAILABLE_YET,
  // 06 page and export
  'page-properties': registerFeature('page-properties'),
  'export-zip': NOT_AVAILABLE_YET,
  'css-variables-tokens': NOT_AVAILABLE_YET,
  'export-bem-css': NOT_AVAILABLE_YET,
  // 07 elements
  'elements-structure': NOT_AVAILABLE_YET,
  'elements-text': NOT_AVAILABLE_YET,
  'elements-lists': NOT_AVAILABLE_YET,
  'nesting-grammar': NOT_AVAILABLE_YET,
  'nesting-grammar-structure': NOT_AVAILABLE_YET,
  'elements-tables': NOT_AVAILABLE_YET,
  'table-commands': NOT_AVAILABLE_YET,
  'elements-form-structure': NOT_AVAILABLE_YET,
  'element-attributes-aria': NOT_AVAILABLE_YET,
  'shared-style-classes': NOT_AVAILABLE_YET,
  'elements-form-inputs': NOT_AVAILABLE_YET,
  'elements-form-inputs-rules': NOT_AVAILABLE_YET,
  'elements-form-controls': NOT_AVAILABLE_YET,
  'elements-media-images': NOT_AVAILABLE_YET,
  'elements-media-embeds': NOT_AVAILABLE_YET,
  'elements-svg-shapes': NOT_AVAILABLE_YET,
  'elements-interactive': NOT_AVAILABLE_YET,
  'natural-child-command': NOT_AVAILABLE_YET,
  'props-element-specific': NOT_AVAILABLE_YET,
  // 08 templates and components
  'templates-layout': NOT_AVAILABLE_YET,
  'templates-content': NOT_AVAILABLE_YET,
  'templates-sections': NOT_AVAILABLE_YET,
  'reusable-components': NOT_AVAILABLE_YET,
  'templates-components': NOT_AVAILABLE_YET,
  // 09 panels
  'palette-search-groups': NOT_AVAILABLE_YET,
  'palette-density': NOT_AVAILABLE_YET,
  'layers-expand-collapse-all': NOT_AVAILABLE_YET,
  'layers-search': NOT_AVAILABLE_YET,
  'layers-row-columns': NOT_AVAILABLE_YET,
  'layers-row-colours': NOT_AVAILABLE_YET,
  // 10 view and positioning
  'zoom-keyboard-buttons': NOT_AVAILABLE_YET,
  'rotation-handle': NOT_AVAILABLE_YET,
  'zoom-wheel-pan': NOT_AVAILABLE_YET,
  rulers: NOT_AVAILABLE_YET,
  'guides-manual': NOT_AVAILABLE_YET,
  'canvas-outlines-zones': NOT_AVAILABLE_YET,
  'layout-grid-overlay': NOT_AVAILABLE_YET,
  'workspace-settings-dialog': NOT_AVAILABLE_YET,
  'absolute-free-drag': NOT_AVAILABLE_YET,
  'absolute-nudge': NOT_AVAILABLE_YET,
  'absolute-anchors': NOT_AVAILABLE_YET,
  'align-distribute': NOT_AVAILABLE_YET,
  'snap-toggle-settings': NOT_AVAILABLE_YET,
  'snap-while-moving': NOT_AVAILABLE_YET,
  'smart-guides': NOT_AVAILABLE_YET,
  'hover-measure': NOT_AVAILABLE_YET,
  // 11 responsive and states
  'breakpoints-switch': NOT_AVAILABLE_YET,
  'breakpoint-overrides': NOT_AVAILABLE_YET,
  'state-styles': NOT_AVAILABLE_YET,
  // 12 preview, embed, theme
  'preview-mode': NOT_AVAILABLE_YET,
  'embed-html': NOT_AVAILABLE_YET,
  'theme-switch': NOT_AVAILABLE_YET,
  // 13 workspace
  'dock-toggles': NOT_AVAILABLE_YET,
  'command-bar': NOT_AVAILABLE_YET,
  'command-bar-set-property': NOT_AVAILABLE_YET,
  'shortcuts-panel': NOT_AVAILABLE_YET,
  'workbench-panel': NOT_AVAILABLE_YET,
  'panel-resize': NOT_AVAILABLE_YET,
  'floating-panels': NOT_AVAILABLE_YET,
  'panel-combine-tabs': NOT_AVAILABLE_YET,
  'workspace-persist-reset': NOT_AVAILABLE_YET,
  'status-bar': NOT_AVAILABLE_YET,
  // 14 accessibility and keyboard
  'accessibility-checks': NOT_AVAILABLE_YET,
  'keyboard-panel-navigation': NOT_AVAILABLE_YET,
  'layers-keyboard-navigation': NOT_AVAILABLE_YET,
  // 15 clipboard and styles
  'clipboard-cut-system': NOT_AVAILABLE_YET,
  'copy-paste-styles': NOT_AVAILABLE_YET,
  // 16 HTML import
  'html-import-structure': NOT_AVAILABLE_YET,
  'html-import-cleaning': NOT_AVAILABLE_YET,
  'html-import-styles': NOT_AVAILABLE_YET,
  'html-import-media-queries': NOT_AVAILABLE_YET,
  'html-import-states': NOT_AVAILABLE_YET,
  'html-import-roundtrip': NOT_AVAILABLE_YET,
  'clipboard-paste-external': NOT_AVAILABLE_YET,
  // 17 code panel
  'code-panel-view': NOT_AVAILABLE_YET,
  'code-panel-selection-sync': NOT_AVAILABLE_YET,
  'code-panel-copy-download': NOT_AVAILABLE_YET,
  'code-panel-edit-css': NOT_AVAILABLE_YET,
  'code-panel-edit-html': NOT_AVAILABLE_YET,
  // 18 animation and events
  'timeline-animations': NOT_AVAILABLE_YET,
  'timeline-keyframes': NOT_AVAILABLE_YET,
  'timeline-animation-settings': NOT_AVAILABLE_YET,
  'timeline-preview': NOT_AVAILABLE_YET,
  'export-keyframes': NOT_AVAILABLE_YET,
  'events-actions': NOT_AVAILABLE_YET,
  'export-events-js': NOT_AVAILABLE_YET,
  // 19 pages, files, assets
  'explorer-pages': NOT_AVAILABLE_YET,
  'explorer-file-system': NOT_AVAILABLE_YET,
  'link-picker': NOT_AVAILABLE_YET,
  'export-multi-page': NOT_AVAILABLE_YET,
  'explorer-assets': NOT_AVAILABLE_YET,
  'explorer-assets-use': NOT_AVAILABLE_YET,
  'export-file-tree': NOT_AVAILABLE_YET,
  'export-assets': NOT_AVAILABLE_YET,
  'page-seo-meta': NOT_AVAILABLE_YET,
  'custom-fonts': NOT_AVAILABLE_YET,
  'explorer-open-folder': NOT_AVAILABLE_YET,
  'code-panel-edit-js': NOT_AVAILABLE_YET,
  // 20 shortcut sweep
  'shortcuts-e2e-sweep': NOT_AVAILABLE_YET,
} as const satisfies FeatureTable;

// Whether a feature is registered as built.
export function isFeatureBuilt(feature: FeatureId): boolean {
  return isRegistered<FeatureId>(FEATURES[feature]);
}
