// The feature table (ARCHITECTURE.md): the one map from every feature of the manifest to its registration, in the
// order of manifest/features/. A feature is registered with registerFeature once it is built, and NOT_AVAILABLE_YET
// until then; a missing or an extra entry is a type error. Its doors, and the controls that stand for an item it
// brings (a palette entry), are usable only while it is registered (DESIGN.md "Build order"); the census fails a
// registered feature with no scenario, or one of whose scenarios cannot run or fails. Plain data: the runner and the
// census read it in Node.
import { NOT_AVAILABLE_YET, isRegistered, registerFeature, type FeatureTable } from '../core/commands/registry.ts';
import type { FeatureId } from '../generated/ids.ts';

export const FEATURES = {
  // 01 foundation
  'editor-shell': registerFeature('editor-shell'),
  'canvas-page-iframe': registerFeature('canvas-page-iframe'),
  // 02 structure editing
  'palette-click-insert': registerFeature('palette-click-insert'),
  'select-click': registerFeature('select-click'),
  'layers-tree': registerFeature('layers-tree'),
  'undo-redo': registerFeature('undo-redo'),
  'delete-element': registerFeature('delete-element'),
  'drag-reorder-canvas': registerFeature('drag-reorder-canvas'),
  'drag-drop-inside': registerFeature('drag-drop-inside'),
  'drag-level-keys-escape': registerFeature('drag-level-keys-escape'),
  'palette-drag-insert': registerFeature('palette-drag-insert'),
  'layers-drag': registerFeature('layers-drag'),
  'move-up-down': registerFeature('move-up-down'),
  'wrap-row-column': registerFeature('wrap-row-column'),
  'drag-side-wrap': registerFeature('drag-side-wrap'),
  'context-menu': registerFeature('context-menu'),
  'nest-into-previous': registerFeature('nest-into-previous'),
  'promote-out': registerFeature('promote-out'),
  duplicate: registerFeature('duplicate'),
  'clipboard-copy-paste': registerFeature('clipboard-copy-paste'),
  'keyboard-tree-walk': registerFeature('keyboard-tree-walk'),
  'hand-keyboard-move': registerFeature('hand-keyboard-move'),
  'text-edit-inline': registerFeature('text-edit-inline'),
  'text-inline-formatting': registerFeature('text-inline-formatting'),
  'rename-element': registerFeature('rename-element'),
  'multi-select-click': registerFeature('multi-select-click'),
  unwrap: registerFeature('unwrap'),
  'marquee-select': registerFeature('marquee-select'),
  'multi-select-actions': NOT_AVAILABLE_YET,
  'select-container-children': registerFeature('select-container-children'),
  'lock-element': registerFeature('lock-element'),
  'hide-element': registerFeature('hide-element'),
  // 03 app and persistence
  'app-menu': registerFeature('app-menu'),
  'ui-language': registerFeature('ui-language'),
  'autosave-restore': registerFeature('autosave-restore'),
  'unsaved-work-guard': registerFeature('unsaved-work-guard'),
  'autosave-crash-recovery': registerFeature('autosave-crash-recovery'),
  'new-blank-page': registerFeature('new-blank-page'),
  'autosave-corruption-recovery': registerFeature('autosave-corruption-recovery'),
  'multi-tab-guard': registerFeature('multi-tab-guard'),
  'project-save-json': registerFeature('project-save-json'),
  'project-open-json': registerFeature('project-open-json'),
  // 04 inspector
  'inspector-panel': registerFeature('inspector-panel'),
  'inspector-number-fields': registerFeature('inspector-number-fields'),
  'props-display': registerFeature('props-display'),
  'props-flex-container': registerFeature('props-flex-container'),
  'props-grid-container': registerFeature('props-grid-container'),
  'props-layout-item': registerFeature('props-layout-item'),
  'props-spacing': registerFeature('props-spacing'),
  'props-size-overflow': registerFeature('props-size-overflow'),
  'props-position': registerFeature('props-position'),
  'color-picker': registerFeature('color-picker'),
  'color-picker-oklch': registerFeature('color-picker-oklch'),
  'color-swatches-eyedropper': registerFeature('color-swatches-eyedropper'),
  'props-typography': registerFeature('props-typography'),
  'props-typography-advanced': registerFeature('props-typography-advanced'),
  'props-background': registerFeature('props-background'),
  'gradient-editor': registerFeature('gradient-editor'),
  'props-border-outline': registerFeature('props-border-outline'),
  'props-effects-basic': registerFeature('props-effects-basic'),
  'shadow-editor': registerFeature('shadow-editor'),
  'props-filters-clip': registerFeature('props-filters-clip'),
  'props-transforms': registerFeature('props-transforms'),
  'props-transition': registerFeature('props-transition'),
  'props-more': registerFeature('props-more'),
  'props-attributes': registerFeature('props-attributes'),
  'inspector-provenance-reset': registerFeature('inspector-provenance-reset'),
  'inspector-property-search': NOT_AVAILABLE_YET,
  'inspector-advanced-mode': registerFeature('inspector-advanced-mode'),
  'inspector-add-property': registerFeature('inspector-add-property'),
  'semantic-tag-switch': registerFeature('semantic-tag-switch'),
  'quick-panel': registerFeature('quick-panel'),
  'multi-select-edit': registerFeature('multi-select-edit'),
  // 05 canvas handles
  'resize-handles': registerFeature('resize-handles'),
  'spacing-handles': registerFeature('spacing-handles'),
  'radius-border-gap-handles': registerFeature('radius-border-gap-handles'),
  'shadow-handles': registerFeature('shadow-handles'),
  // 06 page and export
  'page-properties': registerFeature('page-properties'),
  'export-zip': registerFeature('export-zip'),
  'css-variables-tokens': registerFeature('css-variables-tokens'),
  'export-bem-css': registerFeature('export-bem-css'),
  // 07 elements
  'elements-structure': registerFeature('elements-structure'),
  'elements-text': registerFeature('elements-text'),
  'elements-lists': registerFeature('elements-lists'),
  'nesting-grammar': registerFeature('nesting-grammar'),
  'nesting-grammar-structure': NOT_AVAILABLE_YET,
  'elements-tables': registerFeature('elements-tables'),
  'table-commands': registerFeature('table-commands'),
  'elements-form-structure': registerFeature('elements-form-structure'),
  'element-attributes-aria': registerFeature('element-attributes-aria'),
  'shared-style-classes': registerFeature('shared-style-classes'),
  'elements-form-inputs': registerFeature('elements-form-inputs'),
  'elements-form-inputs-rules': registerFeature('elements-form-inputs-rules'),
  'elements-form-controls': registerFeature('elements-form-controls'),
  'elements-media-images': registerFeature('elements-media-images'),
  'elements-media-embeds': registerFeature('elements-media-embeds'),
  'elements-svg-shapes': registerFeature('elements-svg-shapes'),
  'elements-interactive': registerFeature('elements-interactive'),
  'natural-child-command': registerFeature('natural-child-command'),
  'props-element-specific': registerFeature('props-element-specific'),
  // 08 templates and components
  'templates-layout': registerFeature('templates-layout'),
  'templates-content': registerFeature('templates-content'),
  'templates-sections': registerFeature('templates-sections'),
  'reusable-components': registerFeature('reusable-components'),
  'templates-components': registerFeature('templates-components'),
  // 09 panels
  'palette-search-groups': registerFeature('palette-search-groups'),
  'palette-density': registerFeature('palette-density'),
  'layers-expand-collapse-all': registerFeature('layers-expand-collapse-all'),
  'layers-search': registerFeature('layers-search'),
  'layers-row-columns': registerFeature('layers-row-columns'),
  'layers-row-colours': NOT_AVAILABLE_YET,
  // 10 view and positioning
  'zoom-keyboard-buttons': registerFeature('zoom-keyboard-buttons'),
  'rotation-handle': registerFeature('rotation-handle'),
  'zoom-wheel-pan': registerFeature('zoom-wheel-pan'),
  rulers: registerFeature('rulers'),
  'guides-manual': registerFeature('guides-manual'),
  'canvas-outlines-zones': registerFeature('canvas-outlines-zones'),
  'layout-grid-overlay': registerFeature('layout-grid-overlay'),
  'workspace-settings-dialog': registerFeature('workspace-settings-dialog'),
  'absolute-free-drag': registerFeature('absolute-free-drag'),
  'absolute-nudge': registerFeature('absolute-nudge'),
  'absolute-anchors': registerFeature('absolute-anchors'),
  'align-distribute': registerFeature('align-distribute'),
  'snap-toggle-settings': registerFeature('snap-toggle-settings'),
  'snap-while-moving': registerFeature('snap-while-moving'),
  'smart-guides': registerFeature('smart-guides'),
  'hover-measure': NOT_AVAILABLE_YET,
  // 11 responsive and states
  'breakpoints-switch': registerFeature('breakpoints-switch'),
  'breakpoint-overrides': registerFeature('breakpoint-overrides'),
  'state-styles': registerFeature('state-styles'),
  // 12 preview, embed, theme
  'preview-mode': registerFeature('preview-mode'),
  'embed-html': registerFeature('embed-html'),
  'theme-switch': registerFeature('theme-switch'),
  // 13 workspace
  'dock-toggles': registerFeature('dock-toggles'),
  'command-bar': NOT_AVAILABLE_YET,
  'command-bar-set-property': NOT_AVAILABLE_YET,
  'shortcuts-panel': NOT_AVAILABLE_YET,
  'workbench-panel': registerFeature('workbench-panel'),
  'panel-resize': NOT_AVAILABLE_YET,
  'floating-panels': NOT_AVAILABLE_YET,
  'panel-combine-tabs': NOT_AVAILABLE_YET,
  'workspace-persist-reset': NOT_AVAILABLE_YET,
  'status-bar': NOT_AVAILABLE_YET,
  // 14 accessibility and keyboard
  'accessibility-checks': NOT_AVAILABLE_YET,
  'keyboard-panel-navigation': NOT_AVAILABLE_YET,
  'layers-keyboard-navigation': registerFeature('layers-keyboard-navigation'),
  // 15 clipboard and styles
  'clipboard-cut-system': NOT_AVAILABLE_YET,
  'copy-paste-styles': NOT_AVAILABLE_YET,
  // 16 HTML import
  'html-import-structure': NOT_AVAILABLE_YET,
  'html-import-cleaning': NOT_AVAILABLE_YET,
  'html-import-styles': NOT_AVAILABLE_YET,
  'html-import-media-queries': NOT_AVAILABLE_YET,
  'html-import-states': NOT_AVAILABLE_YET,
  'html-import-roundtrip': NOT_AVAILABLE_YET,
  'clipboard-paste-external': NOT_AVAILABLE_YET,
  // 17 code panel
  'code-panel-view': NOT_AVAILABLE_YET,
  'code-panel-selection-sync': NOT_AVAILABLE_YET,
  'code-panel-copy-download': NOT_AVAILABLE_YET,
  'code-panel-edit-css': NOT_AVAILABLE_YET,
  'code-panel-edit-html': NOT_AVAILABLE_YET,
  // 18 animation and events
  'timeline-animations': NOT_AVAILABLE_YET,
  'timeline-keyframes': NOT_AVAILABLE_YET,
  'timeline-animation-settings': NOT_AVAILABLE_YET,
  'timeline-preview': NOT_AVAILABLE_YET,
  'export-keyframes': NOT_AVAILABLE_YET,
  'events-actions': NOT_AVAILABLE_YET,
  'export-events-js': NOT_AVAILABLE_YET,
  // 19 pages, files, assets
  'explorer-pages': NOT_AVAILABLE_YET,
  'explorer-file-system': NOT_AVAILABLE_YET,
  'link-picker': NOT_AVAILABLE_YET,
  'export-multi-page': NOT_AVAILABLE_YET,
  'explorer-assets': NOT_AVAILABLE_YET,
  'explorer-assets-use': NOT_AVAILABLE_YET,
  'export-file-tree': NOT_AVAILABLE_YET,
  'export-assets': NOT_AVAILABLE_YET,
  'page-seo-meta': NOT_AVAILABLE_YET,
  'custom-fonts': NOT_AVAILABLE_YET,
  'explorer-open-folder': NOT_AVAILABLE_YET,
  'code-panel-edit-js': NOT_AVAILABLE_YET,
  // 20 shortcut sweep
  'shortcuts-e2e-sweep': NOT_AVAILABLE_YET,
} as const satisfies FeatureTable;

// Whether a feature is registered as built.
export function isFeatureBuilt(feature: FeatureId): boolean {
  return isRegistered<FeatureId>(FEATURES[feature]);
}
