// npm run manifest:check [-- --plant <id> | --list-plants]
// Validates manifest/ and the i18n catalogues. Exits 1 on any problem.
import { checkManifest, type ManifestSummary, type Problem } from '../../src/manifest/check.ts';
import { loadManifest } from './load.ts';
import { PLANTS, planted } from './plants.ts';

function printProblems(problems: Problem[]): void {
  for (const p of problems) {
    const where = p.path === '' ? p.file : `${p.file} › ${p.path}`;
    console.log(`✗ [${p.rule}] ${where}: ${p.message}`);
  }
}

function printSummary(s: ManifestSummary): void {
  const kinds = Object.entries(s.doorsByKind).map(([kind, n]) => `${kind} ${n}`).join(', ');
  console.log(`  features     ${s.features} in ${s.featureGroups} groups; status: ${s.features} of ${s.features} missing (status comes only from the runner, which does not exist yet)`);
  console.log(`  commands     ${s.commands}`);
  console.log(`  doors        ${s.doors}: ${kinds}`);
  const placed = Object.values(s.doorsByRegion).reduce((n, x) => n + x, 0);
  console.log(`  placement    ${placed} doors placed in ${s.regions} regions of DESIGN.md, ${s.menuAnchors} menu anchors; the others are keys and pointer gestures (placement none):`);
  for (const [region, n] of Object.entries(s.doorsByRegion)) console.log(`    ${region.padEnd(26)} ${n}`);
  console.log(`  elements     ${s.elements} types, ${s.paletteEntries} palette entries, ${s.attributes} attributes`);
  console.log(`  web data     ${s.generatedProperties} CSS properties (${s.generatedShorthands} shorthands), ${s.generatedElements} HTML elements, generated by npm run gen`);
  console.log(`  properties   ${s.properties} edited properties, ${s.composites} composites, ${s.recipes} compatibility recipes, ${s.structures} structured value types, ${s.couplings} coupling rules`);
  console.log(`  browsers     every edited property and offered keyword supported by Chrome ${s.browsers.chrome}, Firefox ${s.browsers.firefox} and Safari ${s.browsers.safari} (css-compat.json from ${s.compatSource}); ${s.keywordsLeftOut} generated keywords and ${s.unitsLeftOut} generated units left out of offered lists because a browser lacks them`);
  console.log(`  history      ${s.undoableCommands} of ${s.commands} commands undoable`);
  const refs = Object.entries(s.referencesByKind).map(([kind, n]) => `${kind} ${n}`).join(', ');
  console.log(`  references   ${s.plannedReferences} planned, ${s.registeredReferences} registered (${refs})`);
  console.log(`  consumers    ${s.consumers} schema fields, each with a reader`);
  console.log(`  css values   ${s.implementedOnly.length} accepted by the browser syntax (CSSTree's MDN data) where the official syntax rejects them${s.implementedOnly.length > 0 ? `: ${s.implementedOnly.join('; ')}` : ''}`);
  console.log(`  allowlist    ${s.fallbackAllowlist.length} entries, the only values the browser syntax may let through:`);
  for (const entry of s.fallbackAllowlist) console.log(`    - ${entry}`);
  console.log(`  recipes      ${s.recipeSources.join('; ')}; ${s.recipeBrowserSyntax.length} recipe values accepted by the browser syntax only${s.recipeBrowserSyntax.length > 0 ? `: ${s.recipeBrowserSyntax.join('; ')}` : ''}`);
  console.log(`  stored whole ${s.storedWhole.length} shorthands:`);
  for (const entry of s.storedWhole) console.log(`    - ${entry}`);
  console.log(`  interactions ${s.keyContexts} key contexts, ${s.constants} constants, ${s.gestures} gestures`);
  console.log(`  scenarios    ${s.scenarios}`);
  console.log(`  i18n         ${s.i18nKeys} referenced keys, each present in every locale; ${s.glossaryConcepts} glossary concepts, each the label of its property in every locale, and no label names two CSS properties`);
}

const args = process.argv.slice(2);
if (args.includes('--list-plants')) {
  for (const plant of PLANTS) console.log(`${plant.id.padEnd(34)} [${plant.rule}] ${plant.description}`);
  process.exit(0);
}

const loaded = loadManifest();
let input = loaded.input;
const plantAt = args.indexOf('--plant');
if (plantAt >= 0) {
  const id = args[plantAt + 1];
  const plant = PLANTS.find((p) => p.id === id);
  if (!plant) {
    console.log(`unknown plant "${id ?? ''}"; run with --list-plants`);
    process.exit(2);
  }
  console.log(`planted fixture "${plant.id}": ${plant.description} (expected rule: ${plant.rule})`);
  input = planted(input, plant);
}

const result = checkManifest(input);
const problems = [...loaded.problems, ...result.problems];
console.log(`manifest:check: ${Object.keys(input.files).length} manifest files, catalogues ${Object.keys(input.catalogues).join(', ')}`);
if (problems.length > 0) {
  printProblems(problems);
  console.log(`${problems.length} problem${problems.length === 1 ? '' : 's'}. manifest:check FAILED.`);
  process.exit(1);
}
if (result.summary) printSummary(result.summary);
console.log('manifest:check passed.');
